=begin comment

Kubernetes

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1.7.4

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package Net::RawKube::Object::V1Event;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#Event is a report of an event somewhere in the cluster.
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

Kubernetes

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1.7.4

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "Net::RawKube::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => 'Event is a report of an event somewhere in the cluster.',
                                  class => 'V1Event',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'api_version' => {
    	datatype => 'string',
    	base_name => 'apiVersion',
    	description => 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources',
    	format => '',
    	read_only => '',
    		},
    'count' => {
    	datatype => 'int',
    	base_name => 'count',
    	description => 'The number of times this event has occurred.',
    	format => '',
    	read_only => '',
    		},
    'first_timestamp' => {
    	datatype => 'DateTime',
    	base_name => 'firstTimestamp',
    	description => 'The time at which the event was first recorded. (Time of server receipt is in TypeMeta.)',
    	format => '',
    	read_only => '',
    		},
    'involved_object' => {
    	datatype => 'V1ObjectReference',
    	base_name => 'involvedObject',
    	description => 'The object that this event is about.',
    	format => '',
    	read_only => '',
    		},
    'kind' => {
    	datatype => 'string',
    	base_name => 'kind',
    	description => 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds',
    	format => '',
    	read_only => '',
    		},
    'last_timestamp' => {
    	datatype => 'DateTime',
    	base_name => 'lastTimestamp',
    	description => 'The time at which the most recent occurrence of this event was recorded.',
    	format => '',
    	read_only => '',
    		},
    'message' => {
    	datatype => 'string',
    	base_name => 'message',
    	description => 'A human-readable description of the status of this operation.',
    	format => '',
    	read_only => '',
    		},
    'metadata' => {
    	datatype => 'V1ObjectMeta',
    	base_name => 'metadata',
    	description => 'Standard object&#39;s metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata',
    	format => '',
    	read_only => '',
    		},
    'reason' => {
    	datatype => 'string',
    	base_name => 'reason',
    	description => 'This should be a short, machine understandable string that gives the reason for the transition into the object&#39;s current status.',
    	format => '',
    	read_only => '',
    		},
    'source' => {
    	datatype => 'V1EventSource',
    	base_name => 'source',
    	description => 'The component reporting this event. Should be a short machine understandable string.',
    	format => '',
    	read_only => '',
    		},
    'type' => {
    	datatype => 'string',
    	base_name => 'type',
    	description => 'Type of this event (Normal, Warning), new types could be added in the future',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'api_version' => 'string',
    'count' => 'int',
    'first_timestamp' => 'DateTime',
    'involved_object' => 'V1ObjectReference',
    'kind' => 'string',
    'last_timestamp' => 'DateTime',
    'message' => 'string',
    'metadata' => 'V1ObjectMeta',
    'reason' => 'string',
    'source' => 'V1EventSource',
    'type' => 'string'
} );

__PACKAGE__->attribute_map( {
    'api_version' => 'apiVersion',
    'count' => 'count',
    'first_timestamp' => 'firstTimestamp',
    'involved_object' => 'involvedObject',
    'kind' => 'kind',
    'last_timestamp' => 'lastTimestamp',
    'message' => 'message',
    'metadata' => 'metadata',
    'reason' => 'reason',
    'source' => 'source',
    'type' => 'type'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
