=begin comment

Kubernetes

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1.7.4

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package Net::RawKube::Object::V1PodSpec;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#PodSpec is a description of a pod.
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

Kubernetes

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1.7.4

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "Net::RawKube::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => 'PodSpec is a description of a pod.',
                                  class => 'V1PodSpec',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'active_deadline_seconds' => {
    	datatype => 'int',
    	base_name => 'activeDeadlineSeconds',
    	description => 'Optional duration in seconds the pod may be active on the node relative to StartTime before the system will actively try to mark it failed and kill associated containers. Value must be a positive integer.',
    	format => '',
    	read_only => '',
    		},
    'affinity' => {
    	datatype => 'V1Affinity',
    	base_name => 'affinity',
    	description => 'If specified, the pod&#39;s scheduling constraints',
    	format => '',
    	read_only => '',
    		},
    'automount_service_account_token' => {
    	datatype => 'boolean',
    	base_name => 'automountServiceAccountToken',
    	description => 'AutomountServiceAccountToken indicates whether a service account token should be automatically mounted.',
    	format => '',
    	read_only => '',
    		},
    'containers' => {
    	datatype => 'ARRAY[V1Container]',
    	base_name => 'containers',
    	description => 'List of containers belonging to the pod. Containers cannot currently be added or removed. There must be at least one container in a Pod. Cannot be updated.',
    	format => '',
    	read_only => '',
    		},
    'dns_policy' => {
    	datatype => 'string',
    	base_name => 'dnsPolicy',
    	description => 'Set DNS policy for containers within the pod. One of &#39;ClusterFirstWithHostNet&#39;, &#39;ClusterFirst&#39; or &#39;Default&#39;. Defaults to \&quot;ClusterFirst\&quot;. To have DNS options set along with hostNetwork, you have to specify DNS policy explicitly to &#39;ClusterFirstWithHostNet&#39;.',
    	format => '',
    	read_only => '',
    		},
    'host_aliases' => {
    	datatype => 'ARRAY[V1HostAlias]',
    	base_name => 'hostAliases',
    	description => 'HostAliases is an optional list of hosts and IPs that will be injected into the pod&#39;s hosts file if specified. This is only valid for non-hostNetwork pods.',
    	format => '',
    	read_only => '',
    		},
    'host_ipc' => {
    	datatype => 'boolean',
    	base_name => 'hostIPC',
    	description => 'Use the host&#39;s ipc namespace. Optional: Default to false.',
    	format => '',
    	read_only => '',
    		},
    'host_network' => {
    	datatype => 'boolean',
    	base_name => 'hostNetwork',
    	description => 'Host networking requested for this pod. Use the host&#39;s network namespace. If this option is set, the ports that will be used must be specified. Default to false.',
    	format => '',
    	read_only => '',
    		},
    'host_pid' => {
    	datatype => 'boolean',
    	base_name => 'hostPID',
    	description => 'Use the host&#39;s pid namespace. Optional: Default to false.',
    	format => '',
    	read_only => '',
    		},
    'hostname' => {
    	datatype => 'string',
    	base_name => 'hostname',
    	description => 'Specifies the hostname of the Pod If not specified, the pod&#39;s hostname will be set to a system-defined value.',
    	format => '',
    	read_only => '',
    		},
    'image_pull_secrets' => {
    	datatype => 'ARRAY[V1LocalObjectReference]',
    	base_name => 'imagePullSecrets',
    	description => 'ImagePullSecrets is an optional list of references to secrets in the same namespace to use for pulling any of the images used by this PodSpec. If specified, these secrets will be passed to individual puller implementations for them to use. For example, in the case of docker, only DockerConfig type secrets are honored. More info: https://kubernetes.io/docs/concepts/containers/images#specifying-imagepullsecrets-on-a-pod',
    	format => '',
    	read_only => '',
    		},
    'init_containers' => {
    	datatype => 'ARRAY[V1Container]',
    	base_name => 'initContainers',
    	description => 'List of initialization containers belonging to the pod. Init containers are executed in order prior to containers being started. If any init container fails, the pod is considered to have failed and is handled according to its restartPolicy. The name for an init container or normal container must be unique among all containers. Init containers may not have Lifecycle actions, Readiness probes, or Liveness probes. The resourceRequirements of an init container are taken into account during scheduling by finding the highest request/limit for each resource type, and then using the max of of that value or the sum of the normal containers. Limits are applied to init containers in a similar fashion. Init containers cannot currently be added or removed. Cannot be updated. More info: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/',
    	format => '',
    	read_only => '',
    		},
    'node_name' => {
    	datatype => 'string',
    	base_name => 'nodeName',
    	description => 'NodeName is a request to schedule this pod onto a specific node. If it is non-empty, the scheduler simply schedules this pod onto that node, assuming that it fits resource requirements.',
    	format => '',
    	read_only => '',
    		},
    'node_selector' => {
    	datatype => 'HASH[string,string]',
    	base_name => 'nodeSelector',
    	description => 'NodeSelector is a selector which must be true for the pod to fit on a node. Selector which must match a node&#39;s labels for the pod to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/',
    	format => '',
    	read_only => '',
    		},
    'restart_policy' => {
    	datatype => 'string',
    	base_name => 'restartPolicy',
    	description => 'Restart policy for all containers within the pod. One of Always, OnFailure, Never. Default to Always. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy',
    	format => '',
    	read_only => '',
    		},
    'scheduler_name' => {
    	datatype => 'string',
    	base_name => 'schedulerName',
    	description => 'If specified, the pod will be dispatched by specified scheduler. If not specified, the pod will be dispatched by default scheduler.',
    	format => '',
    	read_only => '',
    		},
    'security_context' => {
    	datatype => 'V1PodSecurityContext',
    	base_name => 'securityContext',
    	description => 'SecurityContext holds pod-level security attributes and common container settings. Optional: Defaults to empty.  See type description for default values of each field.',
    	format => '',
    	read_only => '',
    		},
    'service_account' => {
    	datatype => 'string',
    	base_name => 'serviceAccount',
    	description => 'DeprecatedServiceAccount is a depreciated alias for ServiceAccountName. Deprecated: Use serviceAccountName instead.',
    	format => '',
    	read_only => '',
    		},
    'service_account_name' => {
    	datatype => 'string',
    	base_name => 'serviceAccountName',
    	description => 'ServiceAccountName is the name of the ServiceAccount to use to run this pod. More info: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/',
    	format => '',
    	read_only => '',
    		},
    'subdomain' => {
    	datatype => 'string',
    	base_name => 'subdomain',
    	description => 'If specified, the fully qualified Pod hostname will be \&quot;&lt;hostname&gt;.&lt;subdomain&gt;.&lt;pod namespace&gt;.svc.&lt;cluster domain&gt;\&quot;. If not specified, the pod will not have a domainname at all.',
    	format => '',
    	read_only => '',
    		},
    'termination_grace_period_seconds' => {
    	datatype => 'int',
    	base_name => 'terminationGracePeriodSeconds',
    	description => 'Optional duration in seconds the pod needs to terminate gracefully. May be decreased in delete request. Value must be non-negative integer. The value zero indicates delete immediately. If this value is nil, the default grace period will be used instead. The grace period is the duration in seconds after the processes running in the pod are sent a termination signal and the time when the processes are forcibly halted with a kill signal. Set this value longer than the expected cleanup time for your process. Defaults to 30 seconds.',
    	format => '',
    	read_only => '',
    		},
    'tolerations' => {
    	datatype => 'ARRAY[V1Toleration]',
    	base_name => 'tolerations',
    	description => 'If specified, the pod&#39;s tolerations.',
    	format => '',
    	read_only => '',
    		},
    'volumes' => {
    	datatype => 'ARRAY[V1Volume]',
    	base_name => 'volumes',
    	description => 'List of volumes that can be mounted by containers belonging to the pod. More info: https://kubernetes.io/docs/concepts/storage/volumes',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'active_deadline_seconds' => 'int',
    'affinity' => 'V1Affinity',
    'automount_service_account_token' => 'boolean',
    'containers' => 'ARRAY[V1Container]',
    'dns_policy' => 'string',
    'host_aliases' => 'ARRAY[V1HostAlias]',
    'host_ipc' => 'boolean',
    'host_network' => 'boolean',
    'host_pid' => 'boolean',
    'hostname' => 'string',
    'image_pull_secrets' => 'ARRAY[V1LocalObjectReference]',
    'init_containers' => 'ARRAY[V1Container]',
    'node_name' => 'string',
    'node_selector' => 'HASH[string,string]',
    'restart_policy' => 'string',
    'scheduler_name' => 'string',
    'security_context' => 'V1PodSecurityContext',
    'service_account' => 'string',
    'service_account_name' => 'string',
    'subdomain' => 'string',
    'termination_grace_period_seconds' => 'int',
    'tolerations' => 'ARRAY[V1Toleration]',
    'volumes' => 'ARRAY[V1Volume]'
} );

__PACKAGE__->attribute_map( {
    'active_deadline_seconds' => 'activeDeadlineSeconds',
    'affinity' => 'affinity',
    'automount_service_account_token' => 'automountServiceAccountToken',
    'containers' => 'containers',
    'dns_policy' => 'dnsPolicy',
    'host_aliases' => 'hostAliases',
    'host_ipc' => 'hostIPC',
    'host_network' => 'hostNetwork',
    'host_pid' => 'hostPID',
    'hostname' => 'hostname',
    'image_pull_secrets' => 'imagePullSecrets',
    'init_containers' => 'initContainers',
    'node_name' => 'nodeName',
    'node_selector' => 'nodeSelector',
    'restart_policy' => 'restartPolicy',
    'scheduler_name' => 'schedulerName',
    'security_context' => 'securityContext',
    'service_account' => 'serviceAccount',
    'service_account_name' => 'serviceAccountName',
    'subdomain' => 'subdomain',
    'termination_grace_period_seconds' => 'terminationGracePeriodSeconds',
    'tolerations' => 'tolerations',
    'volumes' => 'volumes'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
