=begin comment

Kubernetes

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1.7.4

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('Net::RawKube::ExtensionsV1beta1Api');

my $api = Net::RawKube::ExtensionsV1beta1Api->new();
isa_ok($api, 'Net::RawKube::ExtensionsV1beta1Api');

#
# create_namespaced_daemon_set test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->create_namespaced_daemon_set(namespace => $namespace, body => $body, pretty => $pretty);
}

#
# create_namespaced_deployment test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->create_namespaced_deployment(namespace => $namespace, body => $body, pretty => $pretty);
}

#
# create_namespaced_deployment_rollback test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->create_namespaced_deployment_rollback(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# create_namespaced_ingress test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->create_namespaced_ingress(namespace => $namespace, body => $body, pretty => $pretty);
}

#
# create_namespaced_network_policy test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->create_namespaced_network_policy(namespace => $namespace, body => $body, pretty => $pretty);
}

#
# create_namespaced_replica_set test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->create_namespaced_replica_set(namespace => $namespace, body => $body, pretty => $pretty);
}

#
# create_pod_security_policy test
#
{
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->create_pod_security_policy(body => $body, pretty => $pretty);
}

#
# create_third_party_resource test
#
{
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->create_third_party_resource(body => $body, pretty => $pretty);
}

#
# delete_collection_namespaced_daemon_set test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->delete_collection_namespaced_daemon_set(namespace => $namespace, pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# delete_collection_namespaced_deployment test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->delete_collection_namespaced_deployment(namespace => $namespace, pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# delete_collection_namespaced_ingress test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->delete_collection_namespaced_ingress(namespace => $namespace, pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# delete_collection_namespaced_network_policy test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->delete_collection_namespaced_network_policy(namespace => $namespace, pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# delete_collection_namespaced_replica_set test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->delete_collection_namespaced_replica_set(namespace => $namespace, pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# delete_collection_pod_security_policy test
#
{
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->delete_collection_pod_security_policy(pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# delete_collection_third_party_resource test
#
{
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->delete_collection_third_party_resource(pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# delete_namespaced_daemon_set test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $grace_period_seconds = undef; # replace NULL with a proper value
    my $orphan_dependents = undef; # replace NULL with a proper value
    my $propagation_policy = undef; # replace NULL with a proper value
    my $result = $api->delete_namespaced_daemon_set(name => $name, namespace => $namespace, body => $body, pretty => $pretty, grace_period_seconds => $grace_period_seconds, orphan_dependents => $orphan_dependents, propagation_policy => $propagation_policy);
}

#
# delete_namespaced_deployment test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $grace_period_seconds = undef; # replace NULL with a proper value
    my $orphan_dependents = undef; # replace NULL with a proper value
    my $propagation_policy = undef; # replace NULL with a proper value
    my $result = $api->delete_namespaced_deployment(name => $name, namespace => $namespace, body => $body, pretty => $pretty, grace_period_seconds => $grace_period_seconds, orphan_dependents => $orphan_dependents, propagation_policy => $propagation_policy);
}

#
# delete_namespaced_ingress test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $grace_period_seconds = undef; # replace NULL with a proper value
    my $orphan_dependents = undef; # replace NULL with a proper value
    my $propagation_policy = undef; # replace NULL with a proper value
    my $result = $api->delete_namespaced_ingress(name => $name, namespace => $namespace, body => $body, pretty => $pretty, grace_period_seconds => $grace_period_seconds, orphan_dependents => $orphan_dependents, propagation_policy => $propagation_policy);
}

#
# delete_namespaced_network_policy test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $grace_period_seconds = undef; # replace NULL with a proper value
    my $orphan_dependents = undef; # replace NULL with a proper value
    my $propagation_policy = undef; # replace NULL with a proper value
    my $result = $api->delete_namespaced_network_policy(name => $name, namespace => $namespace, body => $body, pretty => $pretty, grace_period_seconds => $grace_period_seconds, orphan_dependents => $orphan_dependents, propagation_policy => $propagation_policy);
}

#
# delete_namespaced_replica_set test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $grace_period_seconds = undef; # replace NULL with a proper value
    my $orphan_dependents = undef; # replace NULL with a proper value
    my $propagation_policy = undef; # replace NULL with a proper value
    my $result = $api->delete_namespaced_replica_set(name => $name, namespace => $namespace, body => $body, pretty => $pretty, grace_period_seconds => $grace_period_seconds, orphan_dependents => $orphan_dependents, propagation_policy => $propagation_policy);
}

#
# delete_pod_security_policy test
#
{
    my $name = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $grace_period_seconds = undef; # replace NULL with a proper value
    my $orphan_dependents = undef; # replace NULL with a proper value
    my $propagation_policy = undef; # replace NULL with a proper value
    my $result = $api->delete_pod_security_policy(name => $name, body => $body, pretty => $pretty, grace_period_seconds => $grace_period_seconds, orphan_dependents => $orphan_dependents, propagation_policy => $propagation_policy);
}

#
# delete_third_party_resource test
#
{
    my $name = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $grace_period_seconds = undef; # replace NULL with a proper value
    my $orphan_dependents = undef; # replace NULL with a proper value
    my $propagation_policy = undef; # replace NULL with a proper value
    my $result = $api->delete_third_party_resource(name => $name, body => $body, pretty => $pretty, grace_period_seconds => $grace_period_seconds, orphan_dependents => $orphan_dependents, propagation_policy => $propagation_policy);
}

#
# get_api_resources test
#
{
    my $result = $api->get_api_resources();
}

#
# list_daemon_set_for_all_namespaces test
#
{
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->list_daemon_set_for_all_namespaces(field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, pretty => $pretty, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# list_deployment_for_all_namespaces test
#
{
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->list_deployment_for_all_namespaces(field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, pretty => $pretty, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# list_ingress_for_all_namespaces test
#
{
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->list_ingress_for_all_namespaces(field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, pretty => $pretty, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# list_namespaced_daemon_set test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->list_namespaced_daemon_set(namespace => $namespace, pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# list_namespaced_deployment test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->list_namespaced_deployment(namespace => $namespace, pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# list_namespaced_ingress test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->list_namespaced_ingress(namespace => $namespace, pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# list_namespaced_network_policy test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->list_namespaced_network_policy(namespace => $namespace, pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# list_namespaced_replica_set test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->list_namespaced_replica_set(namespace => $namespace, pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# list_network_policy_for_all_namespaces test
#
{
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->list_network_policy_for_all_namespaces(field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, pretty => $pretty, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# list_pod_security_policy test
#
{
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->list_pod_security_policy(pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# list_replica_set_for_all_namespaces test
#
{
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->list_replica_set_for_all_namespaces(field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, pretty => $pretty, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# list_third_party_resource test
#
{
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->list_third_party_resource(pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# patch_namespaced_daemon_set test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->patch_namespaced_daemon_set(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# patch_namespaced_daemon_set_status test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->patch_namespaced_daemon_set_status(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# patch_namespaced_deployment test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->patch_namespaced_deployment(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# patch_namespaced_deployment_scale test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->patch_namespaced_deployment_scale(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# patch_namespaced_deployment_status test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->patch_namespaced_deployment_status(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# patch_namespaced_ingress test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->patch_namespaced_ingress(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# patch_namespaced_ingress_status test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->patch_namespaced_ingress_status(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# patch_namespaced_network_policy test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->patch_namespaced_network_policy(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# patch_namespaced_replica_set test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->patch_namespaced_replica_set(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# patch_namespaced_replica_set_scale test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->patch_namespaced_replica_set_scale(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# patch_namespaced_replica_set_status test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->patch_namespaced_replica_set_status(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# patch_namespaced_replication_controller_dummy_scale test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->patch_namespaced_replication_controller_dummy_scale(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# patch_pod_security_policy test
#
{
    my $name = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->patch_pod_security_policy(name => $name, body => $body, pretty => $pretty);
}

#
# patch_third_party_resource test
#
{
    my $name = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->patch_third_party_resource(name => $name, body => $body, pretty => $pretty);
}

#
# read_namespaced_daemon_set test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $exact = undef; # replace NULL with a proper value
    my $export = undef; # replace NULL with a proper value
    my $result = $api->read_namespaced_daemon_set(name => $name, namespace => $namespace, pretty => $pretty, exact => $exact, export => $export);
}

#
# read_namespaced_daemon_set_status test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->read_namespaced_daemon_set_status(name => $name, namespace => $namespace, pretty => $pretty);
}

#
# read_namespaced_deployment test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $exact = undef; # replace NULL with a proper value
    my $export = undef; # replace NULL with a proper value
    my $result = $api->read_namespaced_deployment(name => $name, namespace => $namespace, pretty => $pretty, exact => $exact, export => $export);
}

#
# read_namespaced_deployment_scale test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->read_namespaced_deployment_scale(name => $name, namespace => $namespace, pretty => $pretty);
}

#
# read_namespaced_deployment_status test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->read_namespaced_deployment_status(name => $name, namespace => $namespace, pretty => $pretty);
}

#
# read_namespaced_ingress test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $exact = undef; # replace NULL with a proper value
    my $export = undef; # replace NULL with a proper value
    my $result = $api->read_namespaced_ingress(name => $name, namespace => $namespace, pretty => $pretty, exact => $exact, export => $export);
}

#
# read_namespaced_ingress_status test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->read_namespaced_ingress_status(name => $name, namespace => $namespace, pretty => $pretty);
}

#
# read_namespaced_network_policy test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $exact = undef; # replace NULL with a proper value
    my $export = undef; # replace NULL with a proper value
    my $result = $api->read_namespaced_network_policy(name => $name, namespace => $namespace, pretty => $pretty, exact => $exact, export => $export);
}

#
# read_namespaced_replica_set test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $exact = undef; # replace NULL with a proper value
    my $export = undef; # replace NULL with a proper value
    my $result = $api->read_namespaced_replica_set(name => $name, namespace => $namespace, pretty => $pretty, exact => $exact, export => $export);
}

#
# read_namespaced_replica_set_scale test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->read_namespaced_replica_set_scale(name => $name, namespace => $namespace, pretty => $pretty);
}

#
# read_namespaced_replica_set_status test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->read_namespaced_replica_set_status(name => $name, namespace => $namespace, pretty => $pretty);
}

#
# read_namespaced_replication_controller_dummy_scale test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->read_namespaced_replication_controller_dummy_scale(name => $name, namespace => $namespace, pretty => $pretty);
}

#
# read_pod_security_policy test
#
{
    my $name = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $exact = undef; # replace NULL with a proper value
    my $export = undef; # replace NULL with a proper value
    my $result = $api->read_pod_security_policy(name => $name, pretty => $pretty, exact => $exact, export => $export);
}

#
# read_third_party_resource test
#
{
    my $name = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $exact = undef; # replace NULL with a proper value
    my $export = undef; # replace NULL with a proper value
    my $result = $api->read_third_party_resource(name => $name, pretty => $pretty, exact => $exact, export => $export);
}

#
# replace_namespaced_daemon_set test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->replace_namespaced_daemon_set(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# replace_namespaced_daemon_set_status test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->replace_namespaced_daemon_set_status(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# replace_namespaced_deployment test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->replace_namespaced_deployment(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# replace_namespaced_deployment_scale test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->replace_namespaced_deployment_scale(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# replace_namespaced_deployment_status test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->replace_namespaced_deployment_status(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# replace_namespaced_ingress test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->replace_namespaced_ingress(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# replace_namespaced_ingress_status test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->replace_namespaced_ingress_status(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# replace_namespaced_network_policy test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->replace_namespaced_network_policy(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# replace_namespaced_replica_set test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->replace_namespaced_replica_set(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# replace_namespaced_replica_set_scale test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->replace_namespaced_replica_set_scale(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# replace_namespaced_replica_set_status test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->replace_namespaced_replica_set_status(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# replace_namespaced_replication_controller_dummy_scale test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->replace_namespaced_replication_controller_dummy_scale(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# replace_pod_security_policy test
#
{
    my $name = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->replace_pod_security_policy(name => $name, body => $body, pretty => $pretty);
}

#
# replace_third_party_resource test
#
{
    my $name = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->replace_third_party_resource(name => $name, body => $body, pretty => $pretty);
}


1;
