=begin comment

Kubernetes

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1.7.4

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('Net::RawKube::LogsApi');

my $api = Net::RawKube::LogsApi->new();
isa_ok($api, 'Net::RawKube::LogsApi');

#
# log_file_handler test
#
{
    my $logpath = undef; # replace NULL with a proper value
    my $result = $api->log_file_handler(logpath => $logpath);
}

#
# log_file_list_handler test
#
{
    my $result = $api->log_file_list_handler();
}


1;
