=begin comment

Kubernetes

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1.7.4

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('Net::RawKube::RbacAuthorizationV1alpha1Api');

my $api = Net::RawKube::RbacAuthorizationV1alpha1Api->new();
isa_ok($api, 'Net::RawKube::RbacAuthorizationV1alpha1Api');

#
# create_cluster_role test
#
{
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->create_cluster_role(body => $body, pretty => $pretty);
}

#
# create_cluster_role_binding test
#
{
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->create_cluster_role_binding(body => $body, pretty => $pretty);
}

#
# create_namespaced_role test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->create_namespaced_role(namespace => $namespace, body => $body, pretty => $pretty);
}

#
# create_namespaced_role_binding test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->create_namespaced_role_binding(namespace => $namespace, body => $body, pretty => $pretty);
}

#
# delete_cluster_role test
#
{
    my $name = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $grace_period_seconds = undef; # replace NULL with a proper value
    my $orphan_dependents = undef; # replace NULL with a proper value
    my $propagation_policy = undef; # replace NULL with a proper value
    my $result = $api->delete_cluster_role(name => $name, body => $body, pretty => $pretty, grace_period_seconds => $grace_period_seconds, orphan_dependents => $orphan_dependents, propagation_policy => $propagation_policy);
}

#
# delete_cluster_role_binding test
#
{
    my $name = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $grace_period_seconds = undef; # replace NULL with a proper value
    my $orphan_dependents = undef; # replace NULL with a proper value
    my $propagation_policy = undef; # replace NULL with a proper value
    my $result = $api->delete_cluster_role_binding(name => $name, body => $body, pretty => $pretty, grace_period_seconds => $grace_period_seconds, orphan_dependents => $orphan_dependents, propagation_policy => $propagation_policy);
}

#
# delete_collection_cluster_role test
#
{
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->delete_collection_cluster_role(pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# delete_collection_cluster_role_binding test
#
{
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->delete_collection_cluster_role_binding(pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# delete_collection_namespaced_role test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->delete_collection_namespaced_role(namespace => $namespace, pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# delete_collection_namespaced_role_binding test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->delete_collection_namespaced_role_binding(namespace => $namespace, pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# delete_namespaced_role test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $grace_period_seconds = undef; # replace NULL with a proper value
    my $orphan_dependents = undef; # replace NULL with a proper value
    my $propagation_policy = undef; # replace NULL with a proper value
    my $result = $api->delete_namespaced_role(name => $name, namespace => $namespace, body => $body, pretty => $pretty, grace_period_seconds => $grace_period_seconds, orphan_dependents => $orphan_dependents, propagation_policy => $propagation_policy);
}

#
# delete_namespaced_role_binding test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $grace_period_seconds = undef; # replace NULL with a proper value
    my $orphan_dependents = undef; # replace NULL with a proper value
    my $propagation_policy = undef; # replace NULL with a proper value
    my $result = $api->delete_namespaced_role_binding(name => $name, namespace => $namespace, body => $body, pretty => $pretty, grace_period_seconds => $grace_period_seconds, orphan_dependents => $orphan_dependents, propagation_policy => $propagation_policy);
}

#
# get_api_resources test
#
{
    my $result = $api->get_api_resources();
}

#
# list_cluster_role test
#
{
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->list_cluster_role(pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# list_cluster_role_binding test
#
{
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->list_cluster_role_binding(pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# list_namespaced_role test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->list_namespaced_role(namespace => $namespace, pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# list_namespaced_role_binding test
#
{
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->list_namespaced_role_binding(namespace => $namespace, pretty => $pretty, field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# list_role_binding_for_all_namespaces test
#
{
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->list_role_binding_for_all_namespaces(field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, pretty => $pretty, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# list_role_for_all_namespaces test
#
{
    my $field_selector = undef; # replace NULL with a proper value
    my $include_uninitialized = undef; # replace NULL with a proper value
    my $label_selector = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $resource_version = undef; # replace NULL with a proper value
    my $timeout_seconds = undef; # replace NULL with a proper value
    my $watch = undef; # replace NULL with a proper value
    my $result = $api->list_role_for_all_namespaces(field_selector => $field_selector, include_uninitialized => $include_uninitialized, label_selector => $label_selector, pretty => $pretty, resource_version => $resource_version, timeout_seconds => $timeout_seconds, watch => $watch);
}

#
# patch_cluster_role test
#
{
    my $name = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->patch_cluster_role(name => $name, body => $body, pretty => $pretty);
}

#
# patch_cluster_role_binding test
#
{
    my $name = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->patch_cluster_role_binding(name => $name, body => $body, pretty => $pretty);
}

#
# patch_namespaced_role test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->patch_namespaced_role(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# patch_namespaced_role_binding test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->patch_namespaced_role_binding(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# read_cluster_role test
#
{
    my $name = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->read_cluster_role(name => $name, pretty => $pretty);
}

#
# read_cluster_role_binding test
#
{
    my $name = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->read_cluster_role_binding(name => $name, pretty => $pretty);
}

#
# read_namespaced_role test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->read_namespaced_role(name => $name, namespace => $namespace, pretty => $pretty);
}

#
# read_namespaced_role_binding test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->read_namespaced_role_binding(name => $name, namespace => $namespace, pretty => $pretty);
}

#
# replace_cluster_role test
#
{
    my $name = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->replace_cluster_role(name => $name, body => $body, pretty => $pretty);
}

#
# replace_cluster_role_binding test
#
{
    my $name = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->replace_cluster_role_binding(name => $name, body => $body, pretty => $pretty);
}

#
# replace_namespaced_role test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->replace_namespaced_role(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}

#
# replace_namespaced_role_binding test
#
{
    my $name = undef; # replace NULL with a proper value
    my $namespace = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $pretty = undef; # replace NULL with a proper value
    my $result = $api->replace_namespaced_role_binding(name => $name, namespace => $namespace, body => $body, pretty => $pretty);
}


1;
